version: "3"

services:
  database:
    image: mysql
    command:
      --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=saya
    volumes:
      - "./mysql/volume:/var/lib/mysql"
  app:
    image: codedayang/saya:0.1.0
    environment:
      - PORT=3000 # 应用启动的端口
      - MYSQL_HOST=database # 数据库地址
      - MYSQL_PORT=3306 # 数据库端口
      - MYSQL_DB=saya # 数据库名
      - MYSQL_USERNAME=root # 数据库账号
      - MYSQL_PASSWORD=root # 数据库密码
    ports:
      - 3000:3000 # 端口映射 
    depends_on:
      - database
    volumes:
      - "./SSLCert:/app/SSLCert"
    restart: always
